# This is a basic workflow to help you get started with Actions

name: OSS-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true
    #- uses: srt32/git-actions@v0.0.3
    #   with:
    #    args: git submodule update --init --recursive
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Build Blog
      run: |
        npm install
        npm install -g hexo-cli
        hexo generate
    - name: Setup aliyun Ossutil
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: oss-cn-beijing.aliyuncs.com
        access-key-id: ${{ secrets.ALY_OSS_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALY_OSS_ACCESS_SECRETS }}
    - name: Print CWD
      run: |
        pwd
        echo ${{ github.workspace }}
        ls -al
    - name: Deply To OSS
      run: ossutil cp -rf ${{ github.workspace }} oss://benbendemo/
